# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FoodinParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foll.Food')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foll.Party')),
            ],
        ),
    ]
