# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0002_food_foodinparty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
