# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0003_auto_20160624_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='datetime',
        ),
    ]
