# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0004_remove_party_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodinparty',
            old_name='party',
            new_name='belong_to_party',
        ),
    ]
