# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 04:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foll', '0007_friendsinparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserinParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_message', models.CharField(max_length=200)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foll.Party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='friendsinparty',
            name='party',
        ),
        migrations.RemoveField(
            model_name='friendsinparty',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendsinParty',
        ),
    ]
