# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0008_auto_20160629_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinparty',
            name='invite_message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
