# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0009_auto_20160629_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinparty',
            name='invitation_accepted',
            field=models.IntegerField(default=0),
        ),
    ]
