# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 01:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foll', '0010_userinparty_invitation_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinparty',
            name='invited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinparty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
