# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 03:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foll', '0012_food_brought_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodinparty',
            name='belong_to_party',
        ),
        migrations.AddField(
            model_name='food',
            name='belong_to_party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foll.Party'),
        ),
        migrations.AddField(
            model_name='foodinparty',
            name='rated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinparty',
            name='date_accepted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userinparty',
            name='invite_message',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
