# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0014_auto_20160703_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userinparty',
            name='date_accepted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
