# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0016_auto_20160704_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinparty',
            name='top_rated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 5, 0, 23, 55, 429217)),
        ),
        migrations.AddField(
            model_name='party',
            name='desc',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='party',
            name='max_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='max_size',
            field=models.IntegerField(default=0),
        ),
    ]
