# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0025_auto_20160707_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='party',
            name='max_budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='party',
            name='max_size',
            field=models.IntegerField(),
        ),
    ]
