# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0026_auto_20160707_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinparty',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
