# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0027_auto_20160710_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinparty',
            old_name='id',
            new_name='invitation_id',
        ),
    ]
