# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0029_auto_20160710_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
