# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0030_food_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='location_lat',
            field=models.DecimalField(decimal_places=4, default=43.6629, max_digits=10),
        ),
        migrations.AddField(
            model_name='party',
            name='location_lng',
            field=models.DecimalField(decimal_places=4, default=79.3957, max_digits=10),
        ),
    ]
