# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0032_auto_20160725_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topratedfood',
            old_name='top_rated',
            new_name='top_rated_food',
        ),
    ]
