# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foll', '0033_auto_20160730_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topratedfood',
            name='top_rated_food',
        ),
        migrations.AddField(
            model_name='topratedfood',
            name='top_rated_food_id',
            field=models.IntegerField(default=0),
        ),
    ]
